name: Code Coverage

on:
  push:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Yarn
        run: yarn install

      - name: Run tests
        run: yarn run test:coverage
        
      - name: mock time
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Shanghai'
          timezoneMacos: 'Asia/Shanghai'
          timezoneWindows: 'China Standard Time'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV }}
